### ISSUE TITLE
Correções de grafia Autenticação: /src/auth /auth.service.ts e auth.controller.ts

### ISSUE THREAD

**Issue by artenlf** [bear-system-dev/whyapp-backend#15]
Pessoal, vi alguns errinhos de grafia para corrigir no /src/auth /auth.service.ts, estou passando aqui para vocês:

na **linha 27**:
`if (!isEmailEqual) return new Error('E-amil incorreto');`

Correção:
**`if (!isEmailEqual) return new Error('E-mail incorreto');`**

--
No arquivo /src/auth /auth.controller.ts:
na **linha 86**:
`message: 'Esse email ainda não possue cadastro',`

Correção:
**`message: 'Esse e-mail ainda não possui cadastro',`**

na **linha 131**:
` message: 'Esse email já possue cadastrado',`

Correção:
**` message: 'Esse e-mail já possui cadastro',`**

**Comment by LestterX** [comment]
Obrigado Arten! Erros corrigidos.

Porém, a parte:

```javascript
if (!isEmailEqual) return new Error('E-amil incorreto');
```
Não tem no código, acredito que tenha sido removido em commits anteriores
